### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by ghost**
Thanks for your amazing work!
Have you ever considered to host the translations in [Launchpad](https://wiki.ubuntu.com/Translations/LpProjectConfiguration), this way the translation could be more easily reviewed by Ubuntu Translators?

### CODE REVIEW

**Comment by QtRoS** [comment]
Big thanks!
My skills of git usage are bigger than skills of bzr usage, so I choosed git. AFAIK I can hoste git repo in launchpad, but github is little bit more handy for git (obviously because it was created for git). But I will think about it, thank you ;)

**Comment by QtRoS** [comment]
BTW, did you see this line in README? :)

> AND don't forget to translate both academy.ini.in and academy-settings.ini.in

**Comment by QtRoS** [comment]
Hello!

Can you take a look at my comment https://github.com/QtRoS/academy/pull/3 ?
Thanks in advance.

2016-03-28 0:11 GMT+03:00 Anne017 notifications@github.com:

**Comment by ghost** [comment]
Whoops, I will read README files to the end next time, I will read README files to the end next time, I will... ;) I have done new pull requests.

**Pull request merged**
